feat: Added support for binding ports based on the USB device location
espressif/pytest-embedded pull request #141
Opened 2022-09-29 10:12 UTC by alekseiapa

- Added support for binding ports based on the location of a USB device

Closes https://github.com/espressif/pytest-embedded/issues/118

2022-10-10 02:40 UTC, hfudev requested changes
LGTM! Please also add the fixture `port_location` to let users define it in `pytest.mark.parametrize`, like the other cli options

2022-10-10 02:40 UTC, hfudev commented on pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
> +        port_location: Optional[str] = None,
no need here.

2022-10-10 02:40 UTC, hfudev commented on pytest-embedded-serial/pytest_embedded_serial/serial.py
> +                raise ValueError('The specified port cannot be found in the provided location.')
the error message should be more friendly. and you could use the for...else... to simplify it a bit.

```python
        if port_location:
            for port in list_ports.comports():
                if port.location == port_location:
                    if self.port and port.device != self.port:
                        raise ValueError(f'The specified location {port_location} binds with port {port.device}, not {self.port}')

                    self.port = port.device
                    break
            else:
                raise ValueError(f'The specified location {port_location} cannot be found.')
```

2022-10-10 02:40 UTC, hfudev commented on pytest-embedded-serial/pytest_embedded_serial/serial.py
> +        self.port_location = port_location
doesn't need this attribute

2022-10-10 02:41 UTC, hfudev commented on pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py
> +        port_location: Optional[str] = None,
The kwargs that is not been captured in this subclass `EspSerial` would pass to `Serial` here: https://github.com/espressif/pytest-embedded/blob/main/pytest-embedded-serial-esp/pytest_embedded_serial_esp/serial.py#L117

2022-10-10 04:02 UTC, alekseiapa commented
@hfudev Could you please look over the changes one more time ? Thank you!

2022-10-10 04:36 UTC, hfudev requested changes

2022-10-10 04:36 UTC, hfudev commented on pytest-embedded-serial/pytest_embedded_serial/serial.py
> +        port_location = kwargs.get('port_location', None)
Here the `port_location` from param or cli is not actually been passed. Should be passed here: https://github.com/espressif/pytest-embedded/blob/main/pytest-embedded/pytest_embedded/plugin.py#L859

You may refer to other cli options/fixtures as examples

2022-10-10 04:36 UTC, hfudev commented on pytest-embedded/pytest_embedded/plugin.py
> +    serial_group.addoption('--port-location', help='USB device location string ("<bus>-<port>[-<port>]…")')
```suggestion
    serial_group.addoption('--port-location', help='USB device location string ("<bus>-<port>[-<port>]…"). Default: None')
```

2022-10-10 06:32 UTC, hfudev commented on pytest-embedded/pytest_embedded/plugin.py
> +                    'port_location': port_location,
also need to add this line here: https://github.com/espressif/pytest-embedded/pull/141/files#diff-b5a6b0a6e20cb69a3ce927b538961a62b3a189870fb359992536e7cc2618cfa5R966

2022-10-10 06:45 UTC, alekseiapa commented
Sorry for the inadvertence. There are a quite lot of things that are new to me.

2022-10-11 09:47 UTC, alekseiapa commented
> @alekseiapa https://github.com/espressif/pytest-embedded/actions/runs/3218060372/jobs/5261770866#step:5:786 seems not passing the CI.

It should be solved now

2022-10-11 11:10 UTC, alekseiapa commented
> > @alekseiapa https://github.com/espressif/pytest-embedded/actions/runs/3218060372/jobs/5261770866#step:5:786 seems not passing the CI.
> 
> It should be solved now

@hfudev finally passed CI

2022-10-12 01:04 UTC, merged

2022-10-12 01:04 UTC, hfudev commented
@alekseiapa Thanks for your contribution!