refactor: change logic of threading control in CaseTester for MultiDev
espressif/pytest-embedded pull request #223
Opened 2023-07-26 08:44 UTC by horw

Replaced logic of creating thread
  before: new case every time create new thread
  now: create thread once, and then thread wait for task
#162

2023-08-25 07:08 UTC, horw commented
Hello, I thread part of code, now it works with generator functions

2023-09-01 08:34 UTC, hfudev requested changes
LGTM! The new approach looks good.

Still got some high-level problem.

The merged junit xml looks like this:

```xml
<testcase file="[group dev-0]: components/driver/test_apps/spi/master/main/test_spi_master.c&amp;lt;-------------------&amp;gt;&#10;[group dev-1]: components/driver/test_apps/spi/master/main/test_spi_master.c" line="[group dev-0]: 1603&amp;lt;-------------------&amp;gt;&#10;[group dev-1]: 1603" time="1.859" name="('esp32c6', 'esp32c6').('defaults', 'defaults').SPI_Master:Test multiple devices [dut-0]">
            <system-out>[group dev-0]:
                ... log ...
                &amp;lt;-------------------&amp;gt;
                [group dev-1]:
                ... log ...
        </testcase>
```

Got two places to improve:
1. `[group dev-0]` should be `[dut-0]` to keep consistence
2. The `----------` separator should not be used in attributes, like `file`, `line`

2023-09-01 08:48 UTC, hfudev commented
@ginkgm @L-KAYA PTAL as well.

After this PR got merged, the old `case_tester` used in ESP-IDF could be replaced by this `unity_tester`

The benefits of this approach are:

1. merged junit reports, with stdout (including performance data)
2. correct test case name even app got panic'ed
3. remove thread/process. Support multi OS.

2023-09-01 09:21 UTC, L-KAYA commented
Have went through the code, I love the idea of `iterator`! LGTM!

2023-09-04 03:14 UTC, horw commented on pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
>                      raise e
I think better just leave as is, don't use self.confirm_write. Maybe it will lead to some timeout issues

2023-09-18 08:46 UTC, hfudev approved these changes
LGTM. Let's drop the deprecation warning first, usually it's not a good idea to confuse users...

For the optimization of the timeout calculation, you may do it in a separate PR.

2023-09-19 05:27 UTC, horw commented on pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
> +    def expect_exact(self, pattern, timeout):
done

2023-09-19 05:27 UTC, horw commented on pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
> +    def expect(self, pattern, timeout):
done

2023-09-19 05:38 UTC, horw commented on pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
> +        )
> Besides, I don't think we should consider the wait board test menu time into the timeout seconds. The overall procedure should be something like this:
> 
> ```
> - first time get the test menu (setup, shouldn't consider)
> - run test case (of course should consider)
> - reset and expect the test menu again (setup, shouldn't consider)
> - run next test case...
> - ...
> ```

I agree with this! 
Maybe we just consider about set up default timeout for test menu (now it 90 seconds),  my guess maybe it good to be a env variable?
Run test case time is already taken from  "[lp_core][test_env=generic_multi_device][timeout=150]" but only in run_case, need to add for run_normal, stage, multi...

2023-09-19 05:46 UTC, horw commented
```
FAILED pytest-embedded-idf/tests/test_idf.py::test_dut_run_all_single_board_cases - AssertionError: assert 10.896 < 10.1
```
I've got this error in the pipeline, will check for it

2023-09-19 15:13 UTC, hfudev commented
> ```
> FAILED pytest-embedded-idf/tests/test_idf.py::test_dut_run_all_single_board_cases - AssertionError: assert 10.896 < 10.1
> ```
> 
> ~I've got this error in the pipeline, will check for it~
> 
> p.s. problem was with device reset

oh, somehow I missed it in the review. Glad you found it :)

2023-11-13 13:55 UTC, hfudev commented on pytest-embedded-idf/pytest_embedded_idf/unity_tester.py
> +        )
let's remove this warning.

`warnings.warn` should tell what the developer should do. let's update the docstring to

```python
        Args:
            case: the specific case that parsed in test menu
            reset: whether to perform a hardware reset before running a case
            timeout: timeout in second, setup time excluded  # <-- change here
            start_retry (int): number of retries for a single case when it is failed to start
```

2023-11-23 14:56 UTC, merged

2023-11-23 14:56 UTC, hfudev commented
Thank you @horw LGTM!