feature: Support Arduino in Wokwi
espressif/pytest-embedded pull request #276
Opened 2024-04-24 11:58 UTC by P-R-O-C-H-Y

Adds support for purest-embedded-wokwi to run with Arduino build files.

2024-04-24 12:29 UTC, hfudev requested changes

2024-04-24 12:29 UTC, hfudev commented on pytest-embedded/pytest_embedded/dut_factory.py
> +
I think I gave you a wrong suggestion earlier, adding a `'firmware_resolver': None` here would be enough. The class/kwargs will be injected later.

(don't forget to remove the duplicated codeblocks here)

2024-04-25 07:21 UTC, P-R-O-C-H-Y commented on pytest-embedded/pytest_embedded/dut_factory.py
> +
Done

2024-04-25 07:21 UTC, P-R-O-C-H-Y commented
All fixed and retested.

2024-04-25 07:46 UTC, hfudev requested changes
LGTM! only left one question

2024-04-25 07:49 UTC, hfudev commented
btw, could you rebase on the main branch? the current commits are quite messy

2024-04-25 08:13 UTC, P-R-O-C-H-Y commented
Closing in favour of #277

2024-04-25 08:13 UTC, closed without merging